package ifi.com.model;
// Generated Nov 1, 2017 10:05:12 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountId generated by hbm2java
 */
@Embeddable
public class AccountId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int customerId;
	private int cardId;
	private int accountId;

	public AccountId() {
	}

	public AccountId(int customerId, int cardId, int accountId) {
		this.customerId = customerId;
		this.cardId = cardId;
		this.accountId = accountId;
	}

	@Column(name = "Customer_ID", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "Card_ID", nullable = false)
	public int getCardId() {
		return this.cardId;
	}

	public void setCardId(int cardId) {
		this.cardId = cardId;
	}

	@Column(name = "Account_ID", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountId))
			return false;
		AccountId castOther = (AccountId) other;

		return (this.getCustomerId() == castOther.getCustomerId()) && (this.getCardId() == castOther.getCardId())
				&& (this.getAccountId() == castOther.getAccountId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCustomerId();
		result = 37 * result + this.getCardId();
		result = 37 * result + this.getAccountId();
		return result;
	}

}
