package ifi.com.model;
// Generated Nov 1, 2017 10:05:12 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Card generated by hbm2java
 */
@Entity
@Table(name = "card", catalog = "customercard")
public class Card implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cardId;
	private String cardName;
	private String dateVaildFrom;
	private String dateVaildTo;
	private String otherCardDetails;
	private Set<Account> accounts = new HashSet<Account>(0);

	public Card() {
	}

	public Card(int cardId, String cardName, String dateVaildFrom, String dateVaildTo) {
		this.cardId = cardId;
		this.cardName = cardName;
		this.dateVaildFrom = dateVaildFrom;
		this.dateVaildTo = dateVaildTo;
	}

	public Card(int cardId, String cardName, String dateVaildFrom, String dateVaildTo, String otherCardDetails,
			Set<Account> accounts) {
		this.cardId = cardId;
		this.cardName = cardName;
		this.dateVaildFrom = dateVaildFrom;
		this.dateVaildTo = dateVaildTo;
		this.otherCardDetails = otherCardDetails;
		this.accounts = accounts;
	}

	@Id

	@Column(name = "Card_ID", unique = true, nullable = false)
	public int getCardId() {
		return this.cardId;
	}

	public void setCardId(int cardId) {
		this.cardId = cardId;
	}

	@Column(name = "Card_Name", nullable = false, length = 100)
	public String getCardName() {
		return this.cardName;
	}

	public void setCardName(String cardName) {
		this.cardName = cardName;
	}

	@Column(name = "Date_Vaild_From", nullable = false, length = 100)
	public String getDateVaildFrom() {
		return this.dateVaildFrom;
	}

	public void setDateVaildFrom(String dateVaildFrom) {
		this.dateVaildFrom = dateVaildFrom;
	}

	@Column(name = "Date_Vaild_To", nullable = false, length = 100)
	public String getDateVaildTo() {
		return this.dateVaildTo;
	}

	public void setDateVaildTo(String dateVaildTo) {
		this.dateVaildTo = dateVaildTo;
	}

	@Column(name = "Other_Card_Details")
	public String getOtherCardDetails() {
		return this.otherCardDetails;
	}

	public void setOtherCardDetails(String otherCardDetails) {
		this.otherCardDetails = otherCardDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	@JsonIgnore
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
